# Generated by Django 6.0.1 on 2026-01-08 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliografia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('caveira', models.BooleanField(default=False, verbose_name='Caveira')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Flash Cards',
                'verbose_name_plural': 'Flash Cards',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaCorrelacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Páginas')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('justificativa_resposta_certa', models.TextField(verbose_name='Justificativa da Resposta Correta')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('coluna_a', models.JSONField(help_text="Lista de itens da coluna A em formato JSON. Ex: ['Item 1', 'Item 2', 'Item 3']", verbose_name='Coluna A (Lista de itens)')),
                ('coluna_b', models.JSONField(help_text="Lista de itens da coluna B em formato JSON. Ex: ['Item A', 'Item B', 'Item C']", verbose_name='Coluna B (Lista de itens)')),
                ('resposta_correta', models.JSONField(help_text="Pares corretos em formato JSON. Ex: {'0': '1', '1': '0', '2': '2'}", verbose_name='Resposta Correta (Pares corretos)')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Pergunta de Correlação',
                'verbose_name_plural': 'Perguntas de Correlação',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaMultiplaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Páginas')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('justificativa_resposta_certa', models.TextField(verbose_name='Justificativa da Resposta Correta')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('alternativa_a', models.CharField(max_length=255, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=255, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=255, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=255, verbose_name='Alternativa D')),
                ('resposta_correta', models.CharField(choices=[('a', 'Alternativa A'), ('b', 'Alternativa B'), ('c', 'Alternativa C'), ('d', 'Alternativa D')], max_length=1, verbose_name='Resposta Correta')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Pergunta Múltipla Escolha',
                'verbose_name_plural': 'Perguntas Múltipla Escolha',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaVFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Páginas')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('justificativa_resposta_certa', models.TextField(verbose_name='Justificativa da Resposta Correta')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('afirmacao_verdadeira', models.TextField(blank=True, null=True, verbose_name='Afirmação Verdadeira')),
                ('afirmacao_falsa', models.TextField(blank=True, null=True, verbose_name='Afirmação Falsa')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Pergunta Verdadeiro ou Falso',
                'verbose_name_plural': 'Perguntas Verdadeiro ou Falso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoErradaAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_id', models.IntegerField(verbose_name='ID da Pergunta')),
                ('pergunta_tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo da Pergunta')),
                ('bibliografia_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Bibliografia')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Erro')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Questão Errada Anônima',
                'verbose_name_plural': 'Questões Erradas Anônimas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_id', models.IntegerField(verbose_name='ID da Pergunta')),
                ('pergunta_tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo da Pergunta')),
                ('resposta_usuario', models.JSONField(verbose_name='Resposta do Usuário')),
                ('acertou', models.BooleanField(verbose_name='Acertou')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Resposta')),
                ('bibliografia_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Bibliografia')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Resposta do Usuário',
                'verbose_name_plural': 'Respostas dos Usuários',
                'ordering': ['-timestamp'],
            },
        ),
    ]
