# Generated by Django 5.2.7 on 2025-10-15 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibliografiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('materia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matéria')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de Publicação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bibliografia',
                'verbose_name_plural': 'Bibliografias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaCorrelacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('justificativa_resposta_certa', models.TextField(verbose_name='Justificativa da Resposta Correta')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coluna_a', models.JSONField(help_text="Lista de itens da coluna A em formato JSON. Ex: ['Item 1', 'Item 2', 'Item 3']", verbose_name='Coluna A (Lista de itens)')),
                ('coluna_b', models.JSONField(help_text="Lista de itens da coluna B em formato JSON. Ex: ['Item A', 'Item B', 'Item C']", verbose_name='Coluna B (Lista de itens)')),
                ('resposta_correta', models.JSONField(help_text="Pares corretos em formato JSON. Ex: {'0': '1', '1': '0', '2': '2'}", verbose_name='Resposta Correta (Pares corretos)')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Pergunta de Correlação',
                'verbose_name_plural': 'Perguntas de Correlação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaMultiplaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('justificativa_resposta_certa', models.TextField(verbose_name='Justificativa da Resposta Correta')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternativa_a', models.CharField(max_length=255, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=255, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=255, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=255, verbose_name='Alternativa D')),
                ('resposta_correta', models.CharField(choices=[('a', 'Alternativa A'), ('b', 'Alternativa B'), ('c', 'Alternativa C'), ('d', 'Alternativa D')], max_length=1, verbose_name='Resposta Correta')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Pergunta Múltipla Escolha',
                'verbose_name_plural': 'Perguntas Múltipla Escolha',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaVFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('justificativa_resposta_certa', models.TextField(verbose_name='Justificativa da Resposta Correta')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('vf', 'Verdadeiro ou Falso'), ('correlacao', 'Correlação')], max_length=20, verbose_name='Tipo de Pergunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afirmacao', models.TextField(verbose_name='Afirmação')),
                ('resposta_correta', models.BooleanField(verbose_name='Resposta Correta (Verdadeiro/Falso)')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Pergunta Verdadeiro ou Falso',
                'verbose_name_plural': 'Perguntas Verdadeiro ou Falso',
                'ordering': ['-created_at'],
            },
        ),
    ]
