# Generated by Django 5.2.8 on 2025-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsmodel',
            name='caveira',
            field=models.BooleanField(default=False, verbose_name='Caveira'),
        ),
    ]
