# Generated by Django 5.2.7 on 2025-10-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliografiamodel',
            options={'ordering': ['id'], 'verbose_name': 'Bibliografia', 'verbose_name_plural': 'Bibliografias'},
        ),
        migrations.AlterModelOptions(
            name='perguntacorrelacaomodel',
            options={'ordering': ['id'], 'verbose_name': 'Pergunta de Correlação', 'verbose_name_plural': 'Perguntas de Correlação'},
        ),
        migrations.AlterModelOptions(
            name='perguntamultiplamodel',
            options={'ordering': ['id'], 'verbose_name': 'Pergunta Múltipla Escolha', 'verbose_name_plural': 'Perguntas Múltipla Escolha'},
        ),
        migrations.AlterModelOptions(
            name='perguntavfmodel',
            options={'ordering': ['id'], 'verbose_name': 'Pergunta Verdadeiro ou Falso', 'verbose_name_plural': 'Perguntas Verdadeiro ou Falso'},
        ),
        migrations.RemoveField(
            model_name='bibliografiamodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bibliografiamodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='perguntacorrelacaomodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='perguntacorrelacaomodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='perguntamultiplamodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='perguntamultiplamodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='perguntavfmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='perguntavfmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='perguntacorrelacaomodel',
            name='paginas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Páginas'),
        ),
        migrations.AddField(
            model_name='perguntamultiplamodel',
            name='paginas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Páginas'),
        ),
        migrations.AddField(
            model_name='perguntavfmodel',
            name='paginas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Páginas'),
        ),
        migrations.AlterField(
            model_name='bibliografiamodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
