# Generated by Django 5.2.7 on 2025-10-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_alter_bibliografiamodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliografiamodel',
            name='ano_publicacao',
        ),
    ]
