# Generated by Django 5.2.7 on 2025-10-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_remove_bibliografiamodel_ano_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('assunto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assunto')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Flash Cards',
                'verbose_name_plural': 'Flash Cards',
                'ordering': ['id'],
            },
        ),
    ]
