# Generated by Django 5.2.7 on 2025-11-05 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_flashcardsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsmodel',
            name='ano',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano da Prova'),
        ),
        migrations.AddField(
            model_name='flashcardsmodel',
            name='prova',
            field=models.BooleanField(default=False, verbose_name='Caiu em Prova'),
        ),
    ]
