# Generated by Django 6.0.1 on 2026-01-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliografia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceitosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('palavra_chave', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palavra-chave')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, verbose_name='Ano da Prova')),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bibliografia.capitulosbibliografiamodel', verbose_name='Assunto')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Conceito',
                'verbose_name_plural': 'Conceitos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CronologiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_conflito', models.CharField(max_length=255, verbose_name='Evento / Conflito')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período')),
                ('principais_forcas', models.TextField(blank=True, null=True, verbose_name='Principais Forças / Atores')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado / Impacto')),
                ('consequencias', models.TextField(blank=True, null=True, verbose_name='Consequências Estratégicas')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Cronologia',
                'verbose_name_plural': 'Cronologias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FilosofosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_filosofico', models.CharField(max_length=255, verbose_name='Período Filosófico')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('principais_ideias', models.TextField(blank=True, null=True, verbose_name='Principais Ideias')),
                ('imagem_caminho', models.CharField(blank=True, help_text='Exemplo: assets/img/socrates/img.jpg', max_length=300, null=True, verbose_name='Caminho da Imagem')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Filósofo',
                'verbose_name_plural': 'Filósofos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HiperlinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('mp4', 'MP4'), ('mp3', 'MP3'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Hiperlink',
                'verbose_name_plural': 'Hiperlinks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PresidentesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_presidencial', models.CharField(max_length=255, verbose_name='Período Presidencial')),
                ('presidente', models.CharField(max_length=255, verbose_name='Presidente')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('conflitos_principais', models.TextField(blank=True, null=True, verbose_name='Conflito(s) Principal(is)')),
                ('imagem_caminho', models.CharField(blank=True, help_text='Exemplo: assets/img/roosevelt/img.jpg', max_length=300, null=True, verbose_name='Caminho da Imagem')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bibliografia.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Presidente',
                'verbose_name_plural': 'Presidentes',
                'ordering': ['id'],
            },
        ),
    ]
