# Generated by Django 5.2.7 on 2025-10-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perguntas', '0002_alter_bibliografiamodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceitosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('caiu_em_prova', models.BooleanField(default=False, verbose_name='Caiu em Prova')),
                ('ano_prova', models.IntegerField(blank=True, null=True, verbose_name='Ano da Prova')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Conceito',
                'verbose_name_plural': 'Conceitos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CronologiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_conflito', models.CharField(max_length=255, verbose_name='Evento / Conflito')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período')),
                ('principais_forcas', models.TextField(blank=True, null=True, verbose_name='Principais Forças / Atores')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado / Impacto')),
                ('consequencias', models.TextField(blank=True, null=True, verbose_name='Consequências Estratégicas')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Cronologia',
                'verbose_name_plural': 'Cronologias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FilosofosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_filosofico', models.CharField(max_length=255, verbose_name='Período Filosófico')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('principais_ideias', models.TextField(blank=True, null=True, verbose_name='Principais Ideias')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Filosofos',
                'verbose_name_plural': 'Filosofos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HiperlinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('mp4', 'MP4'), ('mp3', 'MP3'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Hiperlink',
                'verbose_name_plural': 'Hiperlinks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PresidentesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_presidencial', models.CharField(max_length=255, verbose_name='Período Presidencial')),
                ('presidente', models.CharField(max_length=255, verbose_name='Presidente')),
                ('conflitos_principais', models.TextField(blank=True, null=True, verbose_name='Conflito(s) Principal(is)')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perguntas.bibliografiamodel', verbose_name='Bibliografia')),
            ],
            options={
                'verbose_name': 'Presidentes',
                'verbose_name_plural': 'Presidentes',
                'ordering': ['id'],
            },
        ),
    ]
