# Generated by Django 5.2.7 on 2025-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filosofosmodel',
            options={'ordering': ['id'], 'verbose_name': 'Filósofo', 'verbose_name_plural': 'Filósofos'},
        ),
        migrations.AlterModelOptions(
            name='presidentesmodel',
            options={'ordering': ['id'], 'verbose_name': 'Presidente', 'verbose_name_plural': 'Presidentes'},
        ),
        migrations.AddField(
            model_name='filosofosmodel',
            name='imagem_caminho',
            field=models.CharField(blank=True, help_text='Exemplo: assets/img/socrates/img.jpg', max_length=300, null=True, verbose_name='Caminho da Imagem'),
        ),
        migrations.AddField(
            model_name='presidentesmodel',
            name='imagem_caminho',
            field=models.CharField(blank=True, help_text='Exemplo: assets/img/roosevelt/img.jpg', max_length=300, null=True, verbose_name='Caminho da Imagem'),
        ),
    ]
