# Generated by Django 5.2.7 on 2025-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0002_alter_filosofosmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceitosmodel',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='conceitosmodel',
            name='palavra_chave',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Palavra-chave'),
        ),
    ]
