# Generated by Django 5.2.7 on 2025-10-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0003_conceitosmodel_assunto_conceitosmodel_palavra_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentesmodel',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
    ]
