# Generated by Django 5.2.7 on 2025-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='posto_graduacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='uasg',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('consulta', 'Consulta'), ('editor', 'Editor')], max_length=50, verbose_name='Perfil'),
        ),
    ]
